version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "7860:7860"
    environment:
      - API_URL=http://backend:8000
    networks:
      - app_network

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./data.db:/app/data.db
      - ./model.mdl:/app/model.mdl
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
