services:
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "7860:7860"
    environment:
      - API_URL=http://backend:8000
      - HOST=0.0.0.0
      - PORT=8000
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - ./data.db:/app/data.db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://backend:8000/docs" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
